<?php
/**
 * Invoice Transaction Gateway with Modular Plugin set
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * @copyright       Chronolabs Co-Op http://www.chronolabs.com.au/
 * @license         http://www.fsf.org/copyleft/gpl.html GNU public license
 * @package         xpayment
 * @since           2.5.5
 * @author          Simon Roberts <simon@chronolabs.com.au>
 * @translation     Erol Konik <aphex@aphexthemes.com>
 * @translation     Mariane <mariane_antoun@hotmail.com>
 * @translation     Voltan <voltan@xoops.ir>
 * @translation     Ezsky <ezskyyoung@gmail.com>
 * @translation     Richardo Costa <lusopoemas@gmail.com>
 * @translation     Kris_fr <kris@frxoops.org>
 * @version         $Id: permissions.php 11084 2013-02-23 15:44:20Z timgno $
 */	
	include('header.php');
	
	/*$GLOBALS['xoopsTpl']->assign('php_self', $_SERVER['PHP_SELF']);
	
	xoops_loadLanguage('admin', 'xpayment');
		
	$invoice_handler = xoops_getmodulehandler('invoice', 'xpayment');
	
	    $parts = array(	_XPY_AM_INVOICES_ASTOTALING => array('`created`'=>array('value'=>'0', 'operator'=>'>=')),
	    				_XPY_AM_INVOICES_LAST12MONTHS => array('`created`'=>array('value'=>time()-(60*60*24*7*4*12), 'operator'=>'>=')),
	    				_XPY_AM_INVOICES_LAST6MONTHS => array('`created`'=>array('value'=>time()-(60*60*24*7*4*6), 'operator'=>'>=')),
	    				_XPY_AM_INVOICES_LAST3MONTHS => array('`created`'=>array('value'=>time()-(60*60*24*7*4*3), 'operator'=>'>=')),
	    				_XPY_AM_INVOICES_LAST1MONTHS => array('`created`'=>array('value'=>time()-(60*60*24*7*4*1), 'operator'=>'>=')));
	    foreach(array_reverse($parts) as $title => $part) {
		    foreach($invoice_handler->getCurrenciesUsed($part) as $currency) {
		    	if (	$invoice_handler->getSumByField('`grand`', '`mode`','UNPAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)) != '0.00' ||
		    			$invoice_handler->getSumByField('`grand`', '`mode`','PAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)) != '0.00' ||
		    			$invoice_handler->getSumByField('`grand`', '`mode`','CANCEL', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)) != '0.00'
		    		) {
			    	$indexAdmin->addInfoBox(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency));
			    	if ($part['`created`']['value']!=0) {
				    	$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_FROM."</label>", date(_DATESTRING, time()), 'Red');
					    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TO."</label>", date(_DATESTRING, $part['`created`']['value']), 'Red');
			    	}
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_UNPAID." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','UNPAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_PAID." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','PAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_CANCELLED." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','CANCEL', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_INTEREST." $currency</label>", $invoice_handler->getSumByField('`interest`', '1','1', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
					$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_UNPAID_NONE." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'NONE', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_PAID_NONE." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'NONE', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_CANCELLED_NONE." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'NONE', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_UNPAID_COLLECT." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'COLLECT', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_PAID_COLLECT." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'COLLECT', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_CANCELLED_COLLECT." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'COLLECT', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_UNPAID_FRAUD." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'FRAUD', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_PAID_FRAUD." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'FRAUD', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_CANCELLED_FRAUD." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'FRAUD', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_UNPAID_SETTLED." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_PAID_SETTLED." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_CANCELLED_SETTLED." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_UNPAID_DISCOUNTED." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_PAID_DISCOUNTED." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_CANCELLED_DISCOUNTED." $currency</label>", $invoice_handler->getSumByField('`grand`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_UNPAID_DISCOUNTED_AMOUNT." $currency</label>", $invoice_handler->getSumByField('`discount_amount`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_PAID_DISCOUNTED_AMOUNT." $currency</label>", $invoice_handler->getSumByField('`discount_amount`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_CANCELLED_DISCOUNTED_AMOUNT." $currency</label>", $invoice_handler->getSumByField('`discount_amount`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
					$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_UNPAID_DONATED."</label>", $invoice_handler->getSumByField('`grand`', '`mode`','UNPAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`donation`'=>array('value'=>true, 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_PAID_DONATED."</label>", $invoice_handler->getSumByField('`grand`', '`mode`','PAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`donation`'=>array('value'=>true, 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_SUM_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_SUMARE_CANCELLED_DONATED."</label>", $invoice_handler->getSumByField('`grand`', '`mode`','CANCEL', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`donation`'=>array('value'=>true, 'operator'=>'=')))), 'Green');
		    	}
		    	
		    	if (	$invoice_handler->getSumByField('`tax`', '`mode`','UNPAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)) != '0.00' ||
		    			$invoice_handler->getSumByField('`tax`', '`mode`','PAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)) != '0.00' ||
		    			$invoice_handler->getSumByField('`tax`', '`mode`','CANCEL', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)) != '0.00'
		    		) {
			    
				    $indexAdmin->addInfoBox(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency));
			    	if ($part['`created`']['value']!=0) {
				    	$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_FROM."</label>", date(_DATESTRING, time()), 'Red');
					    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TO."</label>", date(_DATESTRING, $part['`created`']['value']), 'Red');
			    	}
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_UNPAID." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','UNPAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_PAID." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','PAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_CANCELLED." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','CANCEL', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
					$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_UNPAID_NONE." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'NONE', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_PAID_NONE." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'NONE', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_CANCELLED_NONE." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'NONE', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_UNPAID_COLLECT." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'COLLECT', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_PAID_COLLECT." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'COLLECT', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_CANCELLED_COLLECT." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'COLLECT', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_UNPAID_FRAUD." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'FRAUD', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_PAID_FRAUD." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'FRAUD', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_CANCELLED_FRAUD." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'FRAUD', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_UNPAID_SETTLED." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_PAID_SETTLED." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_CANCELLED_SETTLED." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_UNPAID_DISCOUNTED." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_PAID_DISCOUNTED." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_CANCELLED_DISCOUNTED." $currency</label>", $invoice_handler->getSumByField('`tax`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_UNPAID_DONATED."</label>", $invoice_handler->getSumByField('`tax`', '`mode`','UNPAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`donation`'=>array('value'=>true, 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_PAID_DONATED."</label>", $invoice_handler->getSumByField('`tax`', '`mode`','PAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`donation`'=>array('value'=>true, 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_TAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TAXARE_CANCELLED_DONATED."</label>", $invoice_handler->getSumByField('`tax`', '`mode`','CANCEL', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`donation`'=>array('value'=>true, 'operator'=>'=')))), 'Green');
		    	}

				if (	$invoice_handler->getAverageByField('`grand`', '`mode`','UNPAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)) != '0.00' ||
		    			$invoice_handler->getAverageByField('`grand`', '`mode`','PAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)) != '0.00' ||
		    			$invoice_handler->getAverageByField('`grand`', '`mode`','CANCEL', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)) != '0.00'
		    		) {
			    		    	
			    	$indexAdmin->addInfoBox(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency));
			    	if ($part['`created`']['value']!=0) {
				    	$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_FROM."</label>", date(_DATESTRING, time()), 'Red');
					    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TO."</label>", date(_DATESTRING, $part['`created`']['value']), 'Red');
			    	}
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_UNPAID." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','UNPAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_PAID." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','PAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_CANCELLED." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','CANCEL', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
					$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_UNPAID_NONE." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'NONE', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_PAID_NONE." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'NONE', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_CANCELLED_NONE." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'NONE', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_UNPAID_COLLECT." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'COLLECT', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_PAID_COLLECT." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'COLLECT', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_CANCELLED_COLLECT." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'COLLECT', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_UNPAID_FRAUD." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'FRAUD', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_PAID_FRAUD." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'FRAUD', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_CANCELLED_FRAUD." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'FRAUD', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_UNPAID_SETTLED." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_PAID_SETTLED." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_CANCELLED_SETTLED." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_UNPAID_DISCOUNTED." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_PAID_DISCOUNTED." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_CANCELLED_DISCOUNTED." $currency</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_UNPAID_DISCOUNTED_AMOUNT." $currency</label>", $invoice_handler->getAverageByField('`discount_amount`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_PAID_DISCOUNTED_AMOUNT." $currency</label>", $invoice_handler->getAverageByField('`discount_amount`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_CANCELLED_DISCOUNTED_AMOUNT." $currency</label>", $invoice_handler->getAverageByField('`discount_amount`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
					$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_UNPAID_DONATED."</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','UNPAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`donation`'=>array('value'=>true, 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_PAID_DONATED."</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','PAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`donation`'=>array('value'=>true, 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_AVG_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_AVGARE_CANCELLED_DONATED."</label>", $invoice_handler->getAverageByField('`grand`', '`mode`','CANCEL', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`donation`'=>array('value'=>true, 'operator'=>'=')))), 'Green');
							    
		    	}
		    	if (	$invoice_handler->getMaximumByField('`grand`', '`mode`','UNPAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)) != '0.00' ||
		    			$invoice_handler->getMaximumByField('`grand`', '`mode`','PAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)) != '0.00' ||
		    			$invoice_handler->getMaximumByField('`grand`', '`mode`','CANCEL', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)) != '0.00'
		    		) {
		    	
				    $indexAdmin->addInfoBox(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency));
			    	if ($part['`created`']['value']!=0) {
				    	$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_FROM."</label>", date(_DATESTRING, time()), 'Red');
					    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TO."</label>", date(_DATESTRING, $part['`created`']['value']), 'Red');
			    	}
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_UNPAID." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','UNPAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_PAID." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','PAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_CANCELLED." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','CANCEL', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
					$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_UNPAID_NONE." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'NONE', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_PAID_NONE." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'NONE', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_CANCELLED_NONE." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'NONE', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_UNPAID_COLLECT." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'COLLECT', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_PAID_COLLECT." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'COLLECT', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_CANCELLED_COLLECT." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'COLLECT', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_UNPAID_FRAUD." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'FRAUD', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_PAID_FRAUD." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'FRAUD', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_CANCELLED_FRAUD." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'FRAUD', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_UNPAID_SETTLED." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_PAID_SETTLED." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_CANCELLED_SETTLED." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_UNPAID_DISCOUNTED." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_PAID_DISCOUNTED." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_CANCELLED_DISCOUNTED." $currency</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_UNPAID_DISCOUNTED_AMOUNT." $currency</label>", $invoice_handler->getMaximumByField('`discount_amount`', '`mode`','UNPAID', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_PAID_DISCOUNTED_AMOUNT." $currency</label>", $invoice_handler->getMaximumByField('`discount_amount`', '`mode`','PAID', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_CANCELLED_DISCOUNTED_AMOUNT." $currency</label>", $invoice_handler->getMaximumByField('`discount_amount`', '`mode`','CANCEL', array_merge(array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')), array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)), 'Green');	    
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_UNPAID_DONATED."</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','UNPAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`donation`'=>array('value'=>true, 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_PAID_DONATED."</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','PAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`donation`'=>array('value'=>true, 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_MAX_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_MAXARE_CANCELLED_DONATED."</label>", $invoice_handler->getMaximumByField('`grand`', '`mode`','CANCEL', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`donation`'=>array('value'=>true, 'operator'=>'=')))), 'Green');
		    	}

		    	if (	$invoice_handler->getCountByField('*', '`mode`','UNPAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)) != '0' ||
		    			$invoice_handler->getCountByField('*', '`mode`','PAID', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)) != '0' ||
		    			$invoice_handler->getCountByField('*', '`mode`','CANCEL', array_merge(array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), $part)) != '0'
		    		) {
				    $indexAdmin->addInfoBox(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency));
			    	if ($part['`created`']['value']!=0) {
				    	$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_FROM."</label>", date(_DATESTRING, time()), 'Red');
					    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_TO."</label>", date(_DATESTRING, $part['`created`']['value']), 'Red');
			    	}
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_UNPAID."</label>", $invoice_handler->getCountByField('*', '`mode`','UNPAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_PAID."</label>", $invoice_handler->getCountByField('*', '`mode`','PAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_CANCELLED."</label>", $invoice_handler->getCountByField('*', '`mode`','CANCEL', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_UNPAID_NONE."</label>", $invoice_handler->getCountByField('*', '`mode`','UNPAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'NONE', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_PAID_NONE."</label>", $invoice_handler->getCountByField('*', '`mode`','PAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'NONE', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_CANCELLED_NONE."</label>", $invoice_handler->getCountByField('*', '`mode`','CANCEL', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'NONE', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_UNPAID_PENDING."</label>", $invoice_handler->getCountByField('*', '`mode`','UNPAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'PENDING', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_PAID_PENDING."</label>", $invoice_handler->getCountByField('*', '`mode`','PAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'PENDING', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_CANCELLED_PENDING."</label>", $invoice_handler->getCountByField('*', '`mode`','CANCEL', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'PENDING', 'operator'=>'=')))), 'Green');
					$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_UNPAID_NOTICE."</label>", $invoice_handler->getCountByField('*', '`mode`','UNPAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'NOTICE', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_PAID_NOTICE."</label>", $invoice_handler->getCountByField('*', '`mode`','PAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'NOTICE', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_CANCELLED_NOTICE."</label>", $invoice_handler->getCountByField('*', '`mode`','CANCEL', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'NOTICE', 'operator'=>'=')))), 'Green');
					$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_UNPAID_COLLECT."</label>", $invoice_handler->getCountByField('*', '`mode`','UNPAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'COLLECT', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_PAID_COLLECT."</label>", $invoice_handler->getCountByField('*', '`mode`','PAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'COLLECT', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_CANCELLED_COLLECT."</label>", $invoice_handler->getCountByField('*', '`mode`','CANCEL', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'COLLECT', 'operator'=>'=')))), 'Green');
					$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_UNPAID_FRAUD."</label>", $invoice_handler->getCountByField('*', '`mode`','UNPAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'FRAUD', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_PAID_FRAUD."</label>", $invoice_handler->getCountByField('*', '`mode`','PAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'FRAUD', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_CANCELLED_FRAUD."</label>", $invoice_handler->getCountByField('*', '`mode`','CANCEL', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'FRAUD', 'operator'=>'=')))), 'Green');
					$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_UNPAID_SETTLED."</label>", $invoice_handler->getCountByField('*', '`mode`','UNPAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_PAID_SETTLED."</label>", $invoice_handler->getCountByField('*', '`mode`','PAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_CANCELLED_SETTLED."</label>", $invoice_handler->getCountByField('*', '`mode`','CANCEL', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')))), 'Green');
					$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_UNPAID_SETTLED."</label>", $invoice_handler->getCountByField('*', '`mode`','UNPAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_PAID_SETTLED."</label>", $invoice_handler->getCountByField('*', '`mode`','PAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_CANCELLED_SETTLED."</label>", $invoice_handler->getCountByField('*', '`mode`','CANCEL', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'SETTLED', 'operator'=>'=')))), 'Green');
					$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_UNPAID_DISCOUNTED."</label>", $invoice_handler->getCountByField('*', '`mode`','UNPAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_PAID_DISCOUNTED."</label>", $invoice_handler->getCountByField('*', '`mode`','PAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_CANCELLED_DISCOUNTED."</label>", $invoice_handler->getCountByField('*', '`mode`','CANCEL', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`remittion`'=>array('value'=>'DISCOUNTED', 'operator'=>'=')))), 'Green');
					$indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_UNPAID_DONATED."</label>", $invoice_handler->getCountByField('*', '`mode`','UNPAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`donation`'=>array('value'=>true, 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_PAID_DONATED."</label>", $invoice_handler->getCountByField('*', '`mode`','PAID', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`donation`'=>array('value'=>true, 'operator'=>'=')))), 'Green');
				    $indexAdmin->addInfoBoxLine(sprintf(_XPY_AM_INVOICES_COUNTS_TOTAL, $title, $currency), "<label>"._XPY_AM_INVOICES_THEREARE_CANCELLED_DONATED."</label>", $invoice_handler->getCountByField('*', '`mode`','CANCEL', array_merge($part, array('`currency`'=>array('value'=>$currency, 'operator'=> '=')), array('`donation`'=>array('value'=>true, 'operator'=>'=')))), 'Green');
		    	}	    
		    }
	    }*/
	        
	echo $adminMenu->addNavigation('index.php');
    echo $adminMenu->renderIndex();
		
xoops_cp_footer();